// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGIea07sUIb_mz4KRG7lIBtB_hdTOjPP4',
    appId: '1:23094005219:web:d54497a14f3b194b0b64d6',
    messagingSenderId: '23094005219',
    projectId: 'movie-app-b7997',
    authDomain: 'movie-app-b7997.firebaseapp.com',
    storageBucket: 'movie-app-b7997.appspot.com',
    measurementId: 'G-Z8DJKLSH49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3Eud_RheaX5y4ctHLigReKppfU7hv4o',
    appId: '1:23094005219:android:f5e68b4fbf7d2edf0b64d6',
    messagingSenderId: '23094005219',
    projectId: 'movie-app-b7997',
    storageBucket: 'movie-app-b7997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_8tTDRpjqlN4Ywgkr_NMAWzDLKSmSUIk',
    appId: '1:23094005219:ios:f22e6faadd03fbb40b64d6',
    messagingSenderId: '23094005219',
    projectId: 'movie-app-b7997',
    storageBucket: 'movie-app-b7997.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_8tTDRpjqlN4Ywgkr_NMAWzDLKSmSUIk',
    appId: '1:23094005219:ios:e1d13a0ea43becb90b64d6',
    messagingSenderId: '23094005219',
    projectId: 'movie-app-b7997',
    storageBucket: 'movie-app-b7997.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
